apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d0yklb2y3-go-gitops
  description: This is GitOps manifest for d0yklb2y3-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=d0yklb2y3-go
    backstage.io/kubernetes-id: d0yklb2y3-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: d0yklb2y3-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:d0yklb2y3-go
